package Information.Geography.Calculations

object PlaceNames {
  
  val countries = Vector(
    "China",
    "India",
    "America",
    "Indonesia",
    "Brazil",
    "Pakistan",
    "Nigeria",
    "Bangladesh",
    "Russia",
    "Mexico",
    "Japan",
    "Ethiopia",
    "Philippines",
    "Vietnam",
    "Egypt",
    "Congo",
    "Iran",
    "Germany",
    "Turkey",
    "Thailand",
    "France",
    "Italy",
    "Tanzania",
    "South Africa",
    "Myanmar",
    "South Korea",
    "Colombia",
    "Kenya",
    "Spain",
    "Ukraine",
    "Argentina",
    "Sudan",
    "Uganda",
    "Algeria",
    "Iraq",
    "Poland",
    "Canada",
    "Morocco",
    "Afghanistan",
    "Saudi Arabia",
    "Peru",
    "Venezuela",
    "Malaysia",
    "Uzbekistan",
    "Mozambique",
    "Nepal",
    "Ghana",
    "Yemen",
    "Angola",
    "Madagascar",
    "North Korea",
    "Australia",
    "Cameroon",
    "Ivory Coast",
    "Taiwan",
    "Niger",
    "Sri Lanka",
    "Romania",
    "Burkina Faso",
    "Syria",
    "Mali",
    "Chile",
    "Malawi",
    "Kazakhstan",
    "Zambia",
    "Netherlands",
    "Guatemala",
    "Ecuador",
    "Zimbabwe",
    "Cambodia",
    "Senegal",
    "Chad",
    "Guinea",
    "Rwanda",
    "Burundi",
    "Tunisia",
    "Benin",
    "Belgium",
    "Somalia",
    "Cuba",
    "Bolivia",
    "Haiti",
    "Greece",
    "Portugal",
    "Azerbaijan",
    "Sweden",
    "Hungary",
    "Belarus",
    "Tajikistan",
    "Serbia",
    "Switzerland",
    "Israel",
    "Honduras",
    "Jordan",
    "Togo"
  )
}
