package Types.BwapiTypes

import bwapi.UpgradeType

object UpgradeTypes {
  val all = List(
    UpgradeType.Adrenal_Glands,
    UpgradeType.Anabolic_Synthesis,
    UpgradeType.Antennae,
    UpgradeType.Apial_Sensors,
    UpgradeType.Apollo_Reactor,
    UpgradeType.Argus_Jewel,
    UpgradeType.Argus_Talisman,
    UpgradeType.Caduceus_Reactor,
    UpgradeType.Carrier_Capacity,
    UpgradeType.Charon_Boosters,
    UpgradeType.Chitinous_Plating,
    UpgradeType.Colossus_Reactor,
    UpgradeType.Gamete_Meiosis,
    UpgradeType.Gravitic_Boosters,
    UpgradeType.Gravitic_Drive,
    UpgradeType.Gravitic_Thrusters,
    UpgradeType.Grooved_Spines,
    UpgradeType.Ion_Thrusters,
    UpgradeType.Khaydarin_Amulet,
    UpgradeType.Khaydarin_Core,
    UpgradeType.Leg_Enhancements,
    UpgradeType.Metabolic_Boost,
    UpgradeType.Metasynaptic_Node,
    UpgradeType.Moebius_Reactor,
    UpgradeType.Muscular_Augments,
    UpgradeType.None,
    UpgradeType.Ocular_Implants,
    UpgradeType.Pneumatized_Carapace,
    UpgradeType.Protoss_Air_Armor,
    UpgradeType.Protoss_Air_Weapons,
    UpgradeType.Protoss_Ground_Armor,
    UpgradeType.Protoss_Ground_Weapons,
    UpgradeType.Protoss_Plasma_Shields,
    UpgradeType.Reaver_Capacity,
    UpgradeType.Scarab_Damage,
    UpgradeType.Sensor_Array,
    UpgradeType.Singularity_Charge,
    UpgradeType.Terran_Infantry_Armor,
    UpgradeType.Terran_Infantry_Weapons,
    UpgradeType.Terran_Ship_Plating,
    UpgradeType.Terran_Ship_Weapons,
    UpgradeType.Terran_Vehicle_Plating,
    UpgradeType.Terran_Vehicle_Weapons,
    UpgradeType.Titan_Reactor,
    UpgradeType.U_238_Shells,
    UpgradeType.Unknown,
    UpgradeType.Ventral_Sacs,
    UpgradeType.Zerg_Carapace,
    UpgradeType.Zerg_Flyer_Attacks,
    UpgradeType.Zerg_Flyer_Carapace,
    UpgradeType.Zerg_Melee_Attacks,
    UpgradeType.Zerg_Missile_Attacks
  )
}